### ISSUE TITLE
compilation issues - openCV3 update

### ISSUE THREAD

**Issue by eLandon** [avilleret/pix_opencv#8]
Hi,
may be related to  #6 

I'm trying to compile latest version on ubuntu 18.10 64 bits. Pd 0.49 and Gem 0.94 fresh build. 
During the build process I get errors on "pix_opencv_lk.h" regarding #include "opencv2/legacy/legacy.hpp".
I'm not really expert in build system but here's what I tried without success
-replacing #include "opencv2/legacy/legacy.hpp" with #include "opencv2/core/core_c.h"
#include "opencv2/imgproc/imgproc_c.h" as you did in openCV3 update commit, brings other errors with undeclared functions
- removing pix_opencv_lk from build, the hard way (I commented all references to it in makefile, makefile.am and makefile.in, maybe it's wrong to do so ?) brings legacy errors on next objects.

Is there anything I'm missing or is it normal disturbance in the process of moving to openCV3 ?

Thank you

**Comment by avilleret** [comment]
could you post the error you get ?
also I don't have much time to spend on this currently
concerning the changes you tried, you shouldn't manually edit `Makefile.in` and `Makefile`  they are generated resp. by `./autogen.sh` and `./configure` scripts.
So if you want to disable an object, remove its source file from `Makefile.am` and them re-run `./autogen.sh` and `./configure` scripts.

**Comment by eLandon** [comment]
Thanks for your answer, I'll post you the error as soon as I'm back under linux, under windows right now.
And I mean no hurry, it was primary meant to be a report.
Thanks for the explaination regading makefiles.

**Comment by vjx** [comment]
Hello, I think I am having the same issue while trying to compile on Ubuntu 18.04.5 LTS.
This is the error:

In file included from pix_opencv_lk.cc:18:0:
pix_opencv_lk.h:20:10: fatal error: opencv2/legacy/legacy.hpp: No such file or directory
 #include "opencv2/legacy/legacy.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:680: recipe for target 'pix_opencv_la-pix_opencv_lk.lo' failed
make[1]: *** [pix_opencv_la-pix_opencv_lk.lo] Error 1
make[1]: Leaving directory '/home/x/Documents/Pd/externals/pix_opencv/src'
Makefile:475: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by avilleret** [comment]
please use that branch instead : 
https://gitlab.com/antoine.villeret/pix_opencv/-/tree/opencv4

This repo should be up-to-date with gitlab"s mirror though

**Comment by vjx** [comment]
I get the same error using that branch ( https://gitlab.com/antoine.villeret/pix_opencv/-/tree/opencv4)

**Comment by avilleret** [comment]
could you detail the steps you made and the error you got ? 

I'm pretty sure it's not the same as the above, since 1. source files have been renamed and 2. the header `opencv2/legacy/legacy.hpp` is not included anymore but in the SURF external which should be disabled.

**Comment by vjx** [comment]
What I did:
git clone https://gitlab.com/antoine.villeret/pix_opencv.git
cd pix_opencv/
./autogen.sh
./configure
make

pix_opencv_lk.h:20:10: fatal error: opencv2/legacy/legacy.hpp: No such file or directory
 #include "opencv2/legacy/legacy.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:680: recipe for target 'pix_opencv_la-pix_opencv_lk.lo' failed
make[1]: *** [pix_opencv_la-pix_opencv_lk.lo] Error 1
make[1]: Leaving directory '/home/x/Documents/Pd/externals/pix_opencv/src'
Makefile:475: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

[https://pastebin.com/deNuMpAX](url)

**Comment by vjx** [comment]
It seems what I did was compile the same branch. How can I compile the one you sent?

**Comment by avilleret** [comment]
you have to checkout the `opencv4` branch with : 

```
git checkout opencv4
```

from the repo folder,
or if you're in a hurry, you can checkout the right branch while cloning with : 

```
git clone --branch=opencv4 --depth=1 https://gitlab.com/antoine.villeret/pix_opencv.git
```

after that, have a look to the readme to get the instruction to build the lib
let me know if you have troubles

**Comment by vjx** [comment]
Hello, it took longer because I had to compile CMake and Opencv 4 but now I get another error:

x@X230:~/Documents/Pd/externals/pix_opencv/build$ cmake ..
-- Found OpenCV: /usr/local (found suitable version "4.4.0", minimum required is "4") found components:  core imgproc video bgsegm objdetect 
-- 'pix_opencv' will be installed in ''
CMake Error at CMakeLists.txt:82 (add_subdirectory):
  The source directory

    /home/x/Documents/Pd/externals/pix_opencv/FaceTracker

  does not contain a CMakeLists.txt file.


-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'pd'
--   Found pd, version 0.51.1
-- Checking for module 'Gem'
--   Found Gem, version 0.94~pre1
-- Configuring incomplete, errors occurred!
See also "/home/x/Documents/Pd/externals/pix_opencv/build/CMakeFiles/CMakeOutput.log".

**Comment by MarioMey** [comment]
I'm very interested compiling pix_opencv in my system (Debian Buster, PurrData). I'm not familiar with opencv, but I understand that pix_opencv is not being updated (I think it requires version 2, my system has version 3 and actual version is 4), so I can't compile and I think I have the same errors of this thread.

So, I stay here for news...

@vjx, @eLandon  if you achieve to compile it, please tell me. Thanks everybody.

**Comment by avilleret** [comment]
FaceTracker is a submodule, you have to initialize manually the submodule if your git client didn't do it for you with : 

    git submodule update --init

Then CMake takes care of configuring and building it.

**Comment by MarioMey** [comment]
I had opened another issue #22 but I closed it and stay here because I think it's the same issue: compiling pix_opencv.

I did `git submodule update --init` and tried to compile, but cmake looked for IO.cc that it was not in FaceTracker/src path. I made a possible workarround: copied that and other files from this [FaceTracker repository](https://github.com/avilleret/FaceTracker) and could compile OK.

The way to compile as says Readme.md in opencv4 branch, only made pix_opencv.pd_linux. Mixing this method with the one that appears in this repository, I could install everything (help files).

Now, I'm testing them... there're some of them that crashes Pd, some of them sometimes are loaded, sometimes aren't :(... I'll keep on doing tests.

[EDIT1]
It's weird. For example, I load pix_opencv_facetracker-help.pd and [pix_opencv_facetracker] can't be loaded. I create [pix_opencv], I close file, open it again: noew [pix_opencv_facetracker] is loaded. Anyway, it crashes Pd 🤷.

**Comment by avilleret** [comment]
I just made a test on a fresh clone with the following : 

    cd /tmp/
    git clone --depth=1 --branch=opencv4 --recursive https://gitlab.com/antoine.villeret/pix_opencv.git
    # the `--recursive` flag above take care of cloning the submodule with the main repo
    cd pix_opencv
    mkdir build && cd build
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig # needed on my system (Archlinux) because Pd & Gem are installed under /usr/local
    cmake ..  -DCMAKE_INSTALL_PREFIX=${PWD}/package
    cmake --build .
    cmake --build . --target install

then I have a almost working package under `/tmp/pix_opencv/build/package/pix_opencv`.
"Almost" because some objects still doesn't work (`pix_opencv_dft` & `pix_opencv_facetracker` at least).

A last note, pix_opencv is a self contained library : all objects are compiled into a single shared library. Then there are several ways to load it into Pd, the most common one is to add `pix_opencv` to library to load on startup in the Pd preferences.

**Comment by MarioMey** [comment]
Yes, I had imagined that every object is inside `pix_opencv`. I could make some functions work (I don't remember which ones), but the main that I need is facetracker... and that object makes PurrData crash always.

And, if **you** can't even make it work, how would I? 🤷

**Comment by avilleret** [comment]
so it seems that your problem is more making facetracker work than compiling pix_opencv right ? 
in that case, please open another thread (but I'm already aware of this limitation) and close this one if your compilation issue have been resolved. Also since Facetracker is a submodule, it would make more sense to report your issue in its own repo instead of here.

Concerning facetracker, it's a very old library (last commit before opencv4 port was in 2012...) and opencv API changes a lot since that. The main drawback is that the C API have been ditched and Facetracker model is based on it. 
So facetracker would work as soon as someone rewrite the model loading part. 

PR & bounty are welcome.

**Comment by MarioMey** [comment]
I didn't open this issue, @eLandon did. S/he would say if it was resolved for him/her.

For FaceTracker... I understand it is **very** unupdated (8 years!). I should see another way to do it. Thanks!
